### ISSUE TITLE
[REFACTOR] gatheringList QA

### ISSUE THREAD

**Issue by picapipicca** [LuckyVicky-2team/frontend#122]
## Description

QA 수정 및 css ( 반응형 ) 수정

## Todo

-   [x] selectBox ui (+ scrollbar)
-   [x] datePicker mobile 선택시 키보드 떠서 캘린더 화면밖으로 이탈하는 문제
-   [x] 반응형 수정
-   [ ] 모임목록 코드 refactor

## ETC

기타 사항
